### ISSUE TITLE
spc file is unreadable code

### ISSUE THREAD

**Issue by qiuhk** [UT-GlobalSeismology/DSMsynTI-mpi#1]
I used gfortran to compile tipsv program and tish program. The spc file generated after running with the original test1.inf is garbled, and it cannot be converted into sac file by spcsac program. I want to know what is the reason.Thanks for your reply.
<img width="827" alt="图片" src="https://github.com/UT-GlobalSeismology/DSMsynTI-mpi/assets/69391252/72db32f2-b222-4ad2-b343-7ec6f41d5f56">

**Comment by otsuruk** [comment]
Thank you for raising the issue. This was because with the default settings, spc files were generated in binary format. I have fixed the default settings to output in ASCII format.
